cargo-features = ["edition2024"]
[package]
name = "demo"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-program = "1.18.0"
constant_time_eq = "=0.4.1"

[lib]
crate-type = ["cdylib", "lib"]
